name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: docker

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/cloudflare-pages-action@1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          script: 'npm run build'
