name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Run your project's build step
      # - name: Build
      #   run: npm install && npm run build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: WebsiteV2 # e.g. 'my-project'
          directory: build # e.g. 'dist'
          gitHubToken: ${{ secrets.TOKEN }}
